name: Bygge Plads
favicon: null
layout_spectrum: 0.5679568268824369
typography_spectrum: 0.35652456199750304
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.07004260155372322
  lightness: 0.4826863408088684
  saturation: 0.17711533000692725
  rhythmicContrast: 0.09454164723865688
purpose: []
